export const images = {
  logo: "/images/SEPL logo.png",
  director: "/images/Director - Sagar Girase.jpeg",
  hero: "/images/projects/Solar Installations.jpeg",
  about: "/images/projects/Solar Installations.jpeg",
  projects: {
    ruralElectrification: "/images/projects/Saubhagya Scheme.jpg",
    solarLighting: "/images/projects/Street Lights 2.jpeg",
    railway: "/images/projects/Indian Railways.png",
    smartVillage: "/images/projects/PWD.jpg",
  },
  associations: {
    pwd: "/images/projects/PWD.jpg",
    msedcl: "/images/projects/MSEDCL.jpg",
    indianRailways: "/images/projects/Indian Railways.png",
    midc: "/images/projects/MIDC.jpg",
    zillaParishad: "/images/projects/Zilla Parishad.jpg",
    saubhagya: "/images/projects/Saubhagya Scheme.jpg",
    jalJeevan: "/images/projects/Jal Jeevan Mission.jpg",
    relianceJio: "/images/projects/Reliance Jio.jpg",
  },
  showcase: [
    "/images/projects/Street Lights 1.jpeg",
    "/images/projects/Solar Installations.jpeg",
    "/images/projects/Water Projects.png",
    "/images/projects/PWD.jpg",
  ],
  gallery: {
    villageDevelopment: "/images/projects/PWD.jpg",
    toilets: "/images/projects/Water Projects.png",
    roPlants: "/images/projects/Jal Jeevan Mission.jpg",
    schools: "/images/projects/Street Lights 3.jpeg",
    streetLights: "/images/projects/Street Lights 1.jpeg",
    streetLightsGallery: [
      "/images/projects/Street Lights 1.jpeg",
      "/images/projects/Street Lights 2.jpeg",
      "/images/projects/Street Lights 3.jpeg",
      "/images/projects/Street Lights 4.jpeg",
      "/images/projects/Street Lights 5.jpeg",
      "/images/projects/Street Lights 6.jpeg",
      "/images/projects/Street Lights 7.jpeg",
    ],
    solar: "/images/projects/Solar Installations.jpeg",
    waterProjects: "/images/projects/Water Projects.png",
    waterProjectsGallery: ["/images/projects/Water Projects.png"],
    beautification: "/images/projects/Street Lights 5.jpeg",
  },
} as const;
